"""leiloes fonte_url unica para upsert idempotente

Revision ID: 149caaaf3a1a
Revises: c2d16bf43f79
Create Date: 2026-05-27 23:07:56.045722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149caaaf3a1a'
down_revision: Union[str, Sequence[str], None] = 'c2d16bf43f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_leiloes_fonte_url', 'leiloes', ['fonte_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leiloes_fonte_url', 'leiloes', type_='unique')
    # ### end Alembic commands ###
