"""criacao das tabelas base

Revision ID: 9b153de46b0b
Revises: 
Create Date: 2026-05-27 21:54:59.093992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src.core.models  # tipo customizado Point usado nas colunas

# revision identifiers, used by Alembic.
revision: str = '9b153de46b0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leiloeiros',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('matricula', sa.Text(), nullable=False),
    sa.Column('uf_matricula', sa.String(length=2), nullable=False),
    sa.Column('junta_comercial', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('site_oficial', sa.Text(), nullable=True),
    sa.Column('plataformas', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula', 'uf_matricula', name='uq_leiloeiros_matricula_uf')
    )
    op.create_index('idx_leiloeiros_uf', 'leiloeiros', ['uf_matricula'], unique=False)
    op.create_table('leiloes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('leiloeiro_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('modalidade', sa.Text(), nullable=True),
    sa.Column('comitente', sa.Text(), nullable=True),
    sa.Column('data_1praca', sa.DateTime(), nullable=True),
    sa.Column('data_2praca', sa.DateTime(), nullable=True),
    sa.Column('edital_url', sa.Text(), nullable=True),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('fonte_url', sa.Text(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'aberto'"), nullable=False),
    sa.CheckConstraint("tipo IN ('judicial', 'extrajudicial')", name='ck_leiloes_tipo'),
    sa.ForeignKeyConstraint(['leiloeiro_id'], ['leiloeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('leilao_id', sa.UUID(), nullable=True),
    sa.Column('numero_lote', sa.Text(), nullable=True),
    sa.Column('tipo_imovel', sa.Text(), nullable=True),
    sa.Column('endereco_completo', sa.Text(), nullable=True),
    sa.Column('cep', sa.Text(), nullable=True),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('bairro', sa.Text(), nullable=True),
    sa.Column('matricula_imovel', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.Column('avaliacao', sa.Numeric(), nullable=True),
    sa.Column('lance_minimo_1', sa.Numeric(), nullable=True),
    sa.Column('lance_minimo_2', sa.Numeric(), nullable=True),
    sa.Column('ocupado', sa.Boolean(), nullable=True),
    sa.Column('divida_iptu', sa.Numeric(), nullable=True),
    sa.Column('divida_condominio', sa.Numeric(), nullable=True),
    sa.Column('fotos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('coordenadas', src.core.models.Point(), nullable=True),
    sa.Column('hash_dedup', sa.Text(), nullable=True),
    sa.Column('score_oportunidade', sa.Numeric(), nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("uf = 'SP'", name='ck_lotes_uf_sp'),
    sa.ForeignKeyConstraint(['leilao_id'], ['leiloes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_dedup', 'leilao_id', name='uq_lotes_dedup_leilao')
    )
    op.create_index('idx_lotes_cidade', 'lotes', ['cidade'], unique=False)
    op.create_index('idx_lotes_dedup', 'lotes', ['hash_dedup'], unique=False)
    op.create_table('resultados',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=True),
    sa.Column('arrematado', sa.Boolean(), nullable=True),
    sa.Column('preco_arremate', sa.Numeric(), nullable=True),
    sa.Column('num_lances', sa.Integer(), nullable=True),
    sa.Column('lance_minimo_2', sa.Numeric(), nullable=True),
    sa.Column('agio', sa.Numeric(), sa.Computed('CASE WHEN preco_arremate IS NOT NULL AND lance_minimo_2 > 0 THEN (preco_arremate / lance_minimo_2 - 1) ELSE NULL END', persisted=True), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_index('idx_lotes_dedup', table_name='lotes')
    op.drop_index('idx_lotes_cidade', table_name='lotes')
    op.drop_table('lotes')
    op.drop_table('leiloes')
    op.drop_index('idx_leiloeiros_uf', table_name='leiloeiros')
    op.drop_table('leiloeiros')
    # ### end Alembic commands ###
