"""fase2 schema: cadastro leiloeiros, uf_leiloeiro, fonte_tipo, lote_fontes

Revision ID: c2d16bf43f79
Revises: 9b153de46b0b
Create Date: 2026-05-27 22:36:55.432030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d16bf43f79'
down_revision: Union[str, Sequence[str], None] = '9b153de46b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote_fontes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=True),
    sa.Column('fonte_origem', sa.Text(), nullable=False),
    sa.Column('fonte_tipo', sa.Text(), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'fonte_url', name='uq_lote_fontes_url')
    )
    op.add_column('leiloeiros', sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('leiloeiros', sa.Column('fonte_cadastro', sa.Text(), nullable=True))
    op.add_column('leiloeiros', sa.Column('visto_em', sa.DateTime(), nullable=True))
    op.add_column('leiloes', sa.Column('uf_leiloeiro', sa.String(length=2), nullable=True))
    op.add_column('leiloes', sa.Column('fonte_tipo', sa.Text(), nullable=True))
    op.create_index('idx_leiloes_fonte_tipo', 'leiloes', ['fonte_tipo'], unique=False)
    op.create_index('idx_leiloes_status', 'leiloes', ['status'], unique=False)
    op.create_index('idx_leiloes_uf_leiloeiro', 'leiloes', ['uf_leiloeiro'], unique=False)
    op.create_index('idx_lotes_score', 'lotes', ['score_oportunidade'], unique=False)
    op.create_index('idx_lotes_tipo_imovel', 'lotes', ['tipo_imovel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lotes_tipo_imovel', table_name='lotes')
    op.drop_index('idx_lotes_score', table_name='lotes')
    op.drop_index('idx_leiloes_uf_leiloeiro', table_name='leiloes')
    op.drop_index('idx_leiloes_status', table_name='leiloes')
    op.drop_index('idx_leiloes_fonte_tipo', table_name='leiloes')
    op.drop_column('leiloes', 'fonte_tipo')
    op.drop_column('leiloes', 'uf_leiloeiro')
    op.drop_column('leiloeiros', 'visto_em')
    op.drop_column('leiloeiros', 'fonte_cadastro')
    op.drop_column('leiloeiros', 'aliases')
    op.drop_table('lote_fontes')
    # ### end Alembic commands ###
